// endpoints.ts
export const endpoints = {
  auth: {
    login: "/login",
    signup: "/signup",
    otp: "/verifyOtp",
    socialLogin: "/socialLoginAndSignUp",
    getCategory: "/getCategories",
    selectCategory: "/selectCategory",
  },
  main: {
    getAllCity: "/getAllCities",
    getEventForYou: "/getEventsForYou",
    getPopularEvents: "/getPopularEvents",
    getEventBrowserByCategory: "/getEventBrowserByCategory",
    getTrips: "/getTrips",
    createTrip: "/createTrip",
    updateTrip: "/updateTrip",
    deleteTrip: "/deleteTrip",
    getTripDetails: "/getTripDetails",
    activityLikeUnlike: "/activity-like-unlike",
    getEventDetails: "/get-event-Details", // Using same endpoint as checkPickupPoints
    getEventDates: "/get-event-dates",
    getEventDatesDetails: "/get-event-dates-details",
    addEventInTrip: "/addEventInTrip",
    checkout: "/checkout",
    getCartList: "/getCartList",
    cartCheckout: "/cart-checkout",
    cartSchema: "/cart-schema",
    getParticipantSchema: "/get-participant-schema",
    cartCustomerInfo: "/cart-customer",
    createOrder: "/create-order",
    createNoPayment: "/create-no-payment",
    downloadVoucher: "/download-voucher",
    removeItemFromCart: "/remove-item-from-cart",
    updateParticipants: "/update-participants",
    updateCart: "/updateCart",
    getOrders: "/getOrders",
    getTripBuddies: "/getTripBuddies",
    getTripBycity: "/getTripBycity",
  },
};
