export default {
  SPLASHSCREEN: "SplashScreen",
  ONBOARDINGSCREEN: "OnboardingScreen",
  ENABLENOTIFICATIONSCREEN: "EnableNotification",
  SIGNINSCREEN: "SignInScreen",
  SIGNUPSCREEN: "SignUpScreen",
  OTPSCREEN: "OtpScreen",
  FORGOTPASSWORDSCREEN: "ForgotPasswordScreen",
  INTERESTS: "Interests",
  BOTTOM_TAB: "BottomTab",
  PRIVACYTERMS: "PrivacyTerms",

  //===============Main Screens =======
  HOME: "Home",
  GROUP: "Group",
  TRIPS: "Trips",
  BOOKING: "Booking",
  BOOKING_DETAILS: "BookingDetails",
  ACCOUNT: "Account",
  SEARCH_CITY: "SearchCity",
  CITY_DETAIL: "CityDetail",
  BROUSE_BY_CATEGORY: "BrouseByCategory",
  ACTIVITY_DETAILS: "ActivityDetails",
  ACTIVITY_DETAILS_CHECK_AVAILABILITY: "ActivityDetailsCheckAvability",
  CREATE_TRIP: "CreateTrip",
  ADD_TO_TRIP: "AddToTrip",
  TRIP_DETAILS: "TripDetails",
  EDIT_TRIP: "EditTrip",
  CALENDAR_VIEW_TRIP_DETAIL: "CalendarViewTripDetail",
  CART: "Cart",
  CART_CUSTOMER_INFO: "CartCustomerInfo",
  NOTIFICATION_SCREEN: "NotificationScreen",
  NOTIFICATION_SETTINGS: "NotificationSettings",
  EDIT_PROFILE: "EditProfile",
  PAYMENT: "Payment",
  SAVED_CARDS: "SavedCards",
  PAYMENT_METHODS: "PaymentMethods",
  ADD_CARD: "AddCard",
  PAYMENT_SUCCESS: "PaymentSuccess",
  CHAT: "Chat",
  AI_CHAT: "AiChat",
  GROUP_DETAILS: "GroupDetails",
  SAVE_CARD: "SaveCard",
  VIEW_AI_CHAT: "ViewAiChat",
  SURPRISES: "Surprises",
  MEMBER_PROFILE: "MemberProfile",
  UPDATE_INTERESTS: "UpdateInterests",
};
