export default {
  SPLASHSCREEN: "SplashScreen",
  ONBOARDINGSCREEN: "OnboardingScreen",
  ENABLENOTIFICATIONSCREEN: "EnableNotification",
  SIGNINSCREEN: "SignInScreen",
  SIGNUPSCREEN: "SignUpScreen",
  OTPSCREEN: "OtpScreen",
  FORGOTPASSWORDSCREEN: "ForgotPasswordScreen",
  INTERESTS: "Interests",
  BOTTOM_TAB: "BottomTab",

  //===============Main Screens =======
  HOME: "Home",
  GROUP: "Group",
  TRIPS: "Trips",
  CHAT: "Chat",
  ACCOUNT: "Account",
  SEARCH_CITY: "SearchCity",
  CITY_DETAIL: "CityDetail",
  BROUSE_BY_CATEGORY: "BrouseByCategory",
  ACTIVITY_DETAILS: "ActivityDetails",
  ACTIVITY_DETAILS_CHECK_AVAILABILITY: "ActivityDetailsCheckAvability",
  CREATE_TRIP: "CreateTrip",
  ADD_TO_TRIP: "AddToTrip",
};
